packages:
  - example

catalog:
  '@arthurfiorette/biomejs-config': '^2.0.1'
  '@biomejs/biome': '^2.2.2'
  '@microsoft/api-extractor': ^7.55.2
  '@playwright/test': ^1.58.0
  '@rsbuild/core': '^1.1.14'
  '@rsbuild/plugin-react': '^1.0.8'
  '@rslib/core': ^0.19.3
  '@rspack/core': ^1.7.4
  '@swc/html': '^1.15.11'
  '@types/node': ^25.1.0
  '@types/react-dom': ^19.2.3
  '@types/react': ^19.2.10
  'husky': '^9.1.7'
  'react-dom': ^19.2.4
  'react': ^19.2.4
  'typescript': ^5.9.3
