packages:
  - example

catalog:
  '@microsoft/api-extractor': ^7.55.2
  '@playwright/test': ^1.58.0
  '@rslib/core': ^0.19.3
  '@rspack/core': ^1.7.4
  '@types/node': ^25.1.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: ^5.9.3
  '@arthurfiorette/biomejs-config': '^2.0.1'
  '@biomejs/biome': '^2.2.2'
  'husky': '^9.1.7'
  '@rsbuild/core': '^1.1.14'
  '@rsbuild/plugin-react': '^1.0.8'
